#!/bin/sh
CLASSPATH=src

for f in lib/*.jar; do
  CLASSPATH=$CLASSPATH:$f
done

if [ "$OSTYPE" = "cygwin" ]; then
	CLASSPATH=`cygpath -wp $CLASSPATH`
fi

java -cp "$CLASSPATH" clojure.main -i script/run.clj
echo
